import type {
  IAbstractFormBaseFieldError,
  IAbstractFormBaseFieldErrors,
} from '@hmcts/opal-frontend-common/components/abstract/abstract-form-base/interfaces';

export interface ICasesCreateCasefileRespondentDetailsFieldErrors extends IAbstractFormBaseFieldErrors {
  create_casefile_respondent_details_title: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_first_names: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_last_name: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_alias_first_names_0: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_alias_last_name_0: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_alias_first_names_1: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_alias_last_name_1: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_alias_first_names_2: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_alias_last_name_2: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_alias_first_names_3: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_alias_last_name_3: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_alias_first_names_4: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_alias_last_name_4: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_date_of_birth: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_national_insurance_number: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_other_personal_information: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_main_email_address: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_other_email_address: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_main_telephone_number: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_other_telephone_number: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_address_line_1: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_address_line_2: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_address_line_3: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_address_line_4: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_address_line_5: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_postal_or_zip_code: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_country_id: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_third_party_name_or_organisation: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_third_party_relationship: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_third_party_reference: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_third_party_address_line_1: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_third_party_address_line_2: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_third_party_address_line_3: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_third_party_address_line_4: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_third_party_address_line_5: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_third_party_postal_or_zip_code: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_third_party_country_id: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_employer_name: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_employee_reference: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_employer_email_address: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_employer_telephone_number: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_employer_address_line_1: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_employer_address_line_2: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_employer_address_line_3: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_employer_address_line_4: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_employer_address_line_5: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_employer_postal_or_zip_code: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_employer_country_id: IAbstractFormBaseFieldError;
  create_casefile_respondent_details_restricted_information_reason: IAbstractFormBaseFieldError;
}
