import type { ICasesCreateCasefilePartyAlias } from '../../interfaces/cases-create-casefile-party-alias.interface';

export interface ICasesCreateCasefileRespondentDetailsFormData {
  create_casefile_respondent_details_title: string | null;
  create_casefile_respondent_details_first_names: string | null;
  create_casefile_respondent_details_last_name: string | null;
  create_casefile_respondent_details_add_aliases: boolean;
  create_casefile_respondent_details_aliases: ICasesCreateCasefilePartyAlias[];
  create_casefile_respondent_details_date_of_birth: string | null;
  create_casefile_respondent_details_national_insurance_number: string | null;
  create_casefile_respondent_details_other_personal_information: string | null;
  create_casefile_respondent_details_main_email_address: string | null;
  create_casefile_respondent_details_other_email_address: string | null;
  create_casefile_respondent_details_main_telephone_number: string | null;
  create_casefile_respondent_details_other_telephone_number: string | null;
  create_casefile_respondent_details_address_line_1: string | null;
  create_casefile_respondent_details_address_line_2: string | null;
  create_casefile_respondent_details_address_line_3: string | null;
  create_casefile_respondent_details_address_line_4: string | null;
  create_casefile_respondent_details_address_line_5: string | null;
  create_casefile_respondent_details_postal_or_zip_code: string | null;
  create_casefile_respondent_details_country_id: number | null;
  create_casefile_respondent_details_send_correspondence_to_third_party: boolean;
  create_casefile_respondent_details_third_party_name_or_organisation: string | null;
  create_casefile_respondent_details_third_party_relationship: string | null;
  create_casefile_respondent_details_third_party_reference: string | null;
  create_casefile_respondent_details_third_party_address_line_1: string | null;
  create_casefile_respondent_details_third_party_address_line_2: string | null;
  create_casefile_respondent_details_third_party_address_line_3: string | null;
  create_casefile_respondent_details_third_party_address_line_4: string | null;
  create_casefile_respondent_details_third_party_address_line_5: string | null;
  create_casefile_respondent_details_third_party_postal_or_zip_code: string | null;
  create_casefile_respondent_details_third_party_country_id: number | null;
  create_casefile_respondent_details_add_employer_details: boolean;
  create_casefile_respondent_details_employer_name: string | null;
  create_casefile_respondent_details_employee_reference: string | null;
  create_casefile_respondent_details_employer_email_address: string | null;
  create_casefile_respondent_details_employer_telephone_number: string | null;
  create_casefile_respondent_details_employer_address_line_1: string | null;
  create_casefile_respondent_details_employer_address_line_2: string | null;
  create_casefile_respondent_details_employer_address_line_3: string | null;
  create_casefile_respondent_details_employer_address_line_4: string | null;
  create_casefile_respondent_details_employer_address_line_5: string | null;
  create_casefile_respondent_details_employer_postal_or_zip_code: string | null;
  create_casefile_respondent_details_employer_country_id: number | null;
  create_casefile_respondent_details_restricted_information: boolean;
  create_casefile_respondent_details_restricted_information_reason: string | null;
}
