const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');

const OPENAPI_SPEC = path.resolve(__dirname, '../openapi/opal-merged.yaml');
const OUTPUT_DIR = path.resolve(__dirname, '../openapi/generated/api-client');
const GENERATOR_CLI = path.resolve(
  __dirname,
  `../node_modules/.bin/openapi-generator-cli${process.platform === 'win32' ? '.cmd' : ''}`,
);

function removeIfPresent(targetPath) {
  if (fs.existsSync(targetPath)) {
    fs.rmSync(targetPath, { recursive: true, force: true });
  }
}

removeIfPresent(OUTPUT_DIR);
fs.mkdirSync(OUTPUT_DIR, { recursive: true });

if (!fs.existsSync(OPENAPI_SPEC)) {
  console.error(`Missing merged OpenAPI spec at ${OPENAPI_SPEC}. Run 'yarn merge:openapi' first.`);
  process.exit(1);
}

if (!fs.existsSync(GENERATOR_CLI)) {
  console.error(`Missing OpenAPI generator binary at ${GENERATOR_CLI}. Install dependencies before running this script.`);
  process.exit(1);
}

console.log(`Generating reference OpenAPI client from ${OPENAPI_SPEC}`);

const result = spawnSync(
  GENERATOR_CLI,
  [
    'generate',
    '-i',
    OPENAPI_SPEC,
    '-g',
    'typescript-fetch',
    '-o',
    OUTPUT_DIR,
    '--skip-validate-spec',
    '--additional-properties=supportsES6=true,modelPropertyNaming=original,withoutRuntimeChecks=true',
  ],
  { stdio: 'inherit' },
);

if (result.status !== 0) {
  process.exit(result.status || 1);
}

for (const relativePath of ['apis', 'docs', 'runtime', '.openapi-generator', '.openapi-generator-ignore', 'runtime.ts']) {
  removeIfPresent(path.join(OUTPUT_DIR, relativePath));
}

const modelsDir = path.join(OUTPUT_DIR, 'models');
const outputIndex = path.join(OUTPUT_DIR, 'index.ts');
const modelsIndex = path.join(modelsDir, 'index.ts');

if (fs.existsSync(modelsIndex)) {
  fs.copyFileSync(modelsIndex, outputIndex);
} else if (!fs.existsSync(outputIndex)) {
  fs.writeFileSync(
    outputIndex,
    [
      '/**',
      " * Reference-only OpenAPI output for opal-rm-frontend.",
      " * Do not import this file into runtime application code.",
      " */",
      '',
    ].join('\n'),
    'utf8',
  );
}

const readmePath = path.join(OUTPUT_DIR, 'README.md');
fs.writeFileSync(
  readmePath,
  [
    '# OpenAPI Reference Output',
    '',
    'This directory is generated by `yarn generate:openapi`.',
    'It is reference-only and must not be imported by runtime application code in `opal-rm-frontend`.',
    '',
  ].join('\n'),
  'utf8',
);

console.log(`Generated reference-only OpenAPI client at ${OUTPUT_DIR}`);
