export const CreateCasefileSelectors = {
  heading: 'h1',
  globalErrorBanner: '.moj-alert--error',
  globalErrorBannerHeading: '.moj-alert--error .moj-alert__heading',
  globalErrorBannerContent: '.moj-alert--error .moj-alert__content',
  caseTypeGroup: '#caseType',
  caseTypeLegend: '#caseType legend',
  caseTypeRadios: 'input[name="caseType"]',
  caseTypeLabels: '#caseType .govuk-radios__label',
  caseTypeRadio: (value: string) => `input[name="caseType"][value="${value}"]`,
  remoInDescription: '#caseType-remo-in-description',
  applicantConditional: '#applicantTypeConditional',
  applicantType: '#applicantType',
  applicantTypeLabel: 'label[for="applicantType"]',
  applicantTypeSelectedOption: '#applicantType option:selected',
  continueButton: '#continue',
  cancelLink: '#cancelCaseType a',
  errorSummary: '.govuk-error-summary',
  errorSummaryLinks: '.govuk-error-summary a',
  caseTypeError: '#caseType-error-message',
  applicantTypeError: '#applicantType-error-message',
  caseDetails: {
    backLink: '.govuk-back-link',
    caption: '.govuk-caption-l',
    heading: 'h1',
    caseTypeRow: '#caseDetailsCaseType',
    caseTypeValue: '#caseDetailsCaseTypeValue',
    applicantTypeRow: '#caseDetailsApplicantType',
    applicantTypeValue: '#caseDetailsApplicantTypeValue',
    taskNames: '.govuk-task-list__name-and-hint',
    partyDetails: '#partyDetails',
    order: '#order',
    additionalInformation: '#additionalInformation',
    respondentItem: '#respondentItem',
    respondentLink: '#respondentItem a',
    respondentStatus: '#respondentStatus',
    applicantItem: '#applicantItem',
    applicantLink: '#applicantItem a',
    applicantStatus: '#applicantStatus',
    centralAuthorityItem: '#centralAuthorityItem',
    centralAuthorityLink: '#centralAuthorityItem a',
    centralAuthorityStatus: '#centralAuthorityStatus',
    orderDetailsItem: '#orderDetailsItem',
    orderDetailsLink: '#orderDetailsItem a',
    orderDetailsStatus: '#orderDetailsStatus',
    orderTermsItem: '#orderTermsItem',
    orderTermsLink: '#orderTermsItem a',
    orderTermsStatus: '#orderTermsStatus',
    interestAndIndexationItem: '#interestAndIndexationItem',
    interestAndIndexationLink: '#interestAndIndexationItem a',
    interestAndIndexationStatus: '#interestAndIndexationStatus',
    managingPaymentsItem: '#managingPaymentsItem',
    managingPaymentsLink: '#managingPaymentsItem a',
    managingPaymentsStatus: '#managingPaymentsStatus',
    commentsAndNotesItem: '#commentsAndNotesItem',
    commentsAndNotesLink: '#commentsAndNotesItem a',
    commentsAndNotesStatus: '#commentsAndNotesStatus',
    blockingGuidance: '#checkCaseBlockingGuidance',
    checkCaseButton: '#checkCaseButton',
    cancelLink: '#cancelCaseCreation',
  },
  respondentDetails: {
    heading: 'h1',
    sectionHeadings: 'h2',
    title: '#respondent_title',
    firstNames: '#respondent_first_names',
    lastName: '#respondent_last_name',
    addAliases: '#respondent_add_aliases',
    aliasesConditional: '#respondentAliasesConditional-conditional',
    aliasFirstNames: 'input[id^="respondent_alias_first_names_"]',
    aliasLastNames: 'input[id^="respondent_alias_last_name_"]',
    aliasFirstName: (index: number) => `#respondent_alias_first_names_${index}`,
    aliasLastName: (index: number) => `#respondent_alias_last_name_${index}`,
    addAliasButton: '#addRespondentAlias',
    removeAliasLink: '#respondentAliasesConditional-conditional a.govuk-link',
    dateOfBirth: '#respondent_date_of_birth',
    nationalInsuranceNumber: '#respondent_national_insurance_number',
    otherPersonalInformation: '#respondent_other_personal_information',
    mainEmailAddress: '#respondent_main_email_address',
    otherEmailAddress: '#respondent_other_email_address',
    mainTelephoneNumber: '#respondent_main_telephone_number',
    otherTelephoneNumber: '#respondent_other_telephone_number',
    addressLine1: '#respondent_address_line_1',
    addressLine2: '#respondent_address_line_2',
    addressLine3: '#respondent_address_line_3',
    addressLine4: '#respondent_address_line_4',
    addressLine5: '#respondent_address_line_5',
    postalOrZipCode: '#respondent_postal_or_zip_code',
    countryId: '#respondent_country_id',
    countryAutocomplete: '#respondent_country_id-autocomplete',
    countryOptions: '#respondent_country_id-autocomplete__listbox [role="option"]',
    sendCorrespondenceToThirdParty: '#respondent_send_correspondence_to_third_party',
    thirdPartyConditional: '#respondentThirdPartyConditional-conditional',
    thirdPartyNameOrOrganisation: '#respondent_third_party_name_or_organisation',
    thirdPartyRelationship: '#respondent_third_party_relationship',
    thirdPartyReference: '#respondent_third_party_reference',
    thirdPartyAddressLine1: '#respondent_third_party_address_line_1',
    thirdPartyAddressLine2: '#respondent_third_party_address_line_2',
    thirdPartyAddressLine3: '#respondent_third_party_address_line_3',
    thirdPartyAddressLine4: '#respondent_third_party_address_line_4',
    thirdPartyAddressLine5: '#respondent_third_party_address_line_5',
    thirdPartyPostalOrZipCode: '#respondent_third_party_postal_or_zip_code',
    thirdPartyCountry: '#respondent_third_party_country_id',
    addEmployerDetails: '#respondent_add_employer_details',
    employerConditional: '#respondentEmployerConditional-conditional',
    employerName: '#respondent_employer_name',
    employeeReference: '#respondent_employee_reference',
    employerEmailAddress: '#respondent_employer_email_address',
    employerTelephoneNumber: '#respondent_employer_telephone_number',
    employerAddressLine1: '#respondent_employer_address_line_1',
    employerAddressLine2: '#respondent_employer_address_line_2',
    employerAddressLine3: '#respondent_employer_address_line_3',
    employerAddressLine4: '#respondent_employer_address_line_4',
    employerAddressLine5: '#respondent_employer_address_line_5',
    employerPostalOrZipCode: '#respondent_employer_postal_or_zip_code',
    employerCountryId: '#respondent_employer_country_id',
    employerCountryAutocomplete: '#respondent_employer_country_id-autocomplete',
    employerCountryOptions: '#respondent_employer_country_id-autocomplete__listbox [role="option"]',
    restrictedInformation: '#respondent_restricted_information',
    restrictedInformationConditional: '#respondentRestrictedInformationConditional-conditional',
    restrictedInformationReason: '#respondent_restricted_information_reason',
    returnToCaseDetails: '#returnToCaseDetails',
    cancelLink: '#cancelRespondentDetails a',
    errorSummary: '.govuk-error-summary',
    errorSummaryLinks: '.govuk-error-summary a',
    firstNamesError: '#respondent_first_names-error-message',
    lastNameError: '#respondent_last_name-error-message',
    aliasFirstNameError: (index: number) => `#respondent_alias_first_names_${index}-error-message`,
    aliasLastNameError: (index: number) => `#respondent_alias_last_name_${index}-error-message`,
    addressLine1Error: '#respondent_address_line_1-error-message',
    countryError: '#respondent_country_id-autocomplete-error-message',
    thirdPartyNameOrOrganisationError: '#respondent_third_party_name_or_organisation-error-message',
    thirdPartyRelationshipError: '#respondent_third_party_relationship-error-message',
    thirdPartyAddressLine1Error: '#respondent_third_party_address_line_1-error-message',
    thirdPartyCountryError: '#respondent_third_party_country_id-error-message',
    employerNameError: '#respondent_employer_name-error-message',
    employerAddressLine1Error: '#respondent_employer_address_line_1-error-message',
    employerCountryError: '#respondent_employer_country_id-autocomplete-error-message',
    restrictedInformationReasonError: '#respondent_restricted_information_reason-error-message',
  },
} as const;
