export const CreateCasefileSelectors = {
  heading: 'h1',
  caseTypeGroup: '#caseType',
  caseTypeLegend: '#caseType legend',
  caseTypeRadios: 'input[name="caseType"]',
  caseTypeLabels: '#caseType .govuk-radios__label',
  caseTypeRadio: (value: string) => `input[name="caseType"][value="${value}"]`,
  remoInDescription: '#caseType-remo-in-description',
  applicantConditional: '#applicantTypeConditional',
  applicantType: '#applicantType',
  applicantTypeLabel: 'label[for="applicantType"]',
  applicantTypeSelectedOption: '#applicantType option:selected',
  continueButton: '#continue',
  cancelLink: '#cancelCaseType a',
  errorSummary: '.govuk-error-summary',
  errorSummaryLinks: '.govuk-error-summary a',
  caseTypeError: '#caseType-error-message',
  applicantTypeError: '#applicantType-error-message',
} as const;
