export const CreateCasefileSelectors = {
  heading: 'h1',
  globalErrorBanner: '.moj-alert--error',
  globalErrorBannerHeading: '.moj-alert--error .moj-alert__heading',
  globalErrorBannerContent: '.moj-alert--error .moj-alert__content',
  caseTypeGroup: '#caseType',
  caseTypeLegend: '#caseType legend',
  caseTypeRadios: 'input[name="caseType"]',
  caseTypeLabels: '#caseType .govuk-radios__label',
  caseTypeRadio: (value: string) => `input[name="caseType"][value="${value}"]`,
  remoInDescription: '#caseType-remo-in-description',
  applicantConditional: '#applicantTypeConditional',
  applicantType: '#applicantType',
  applicantTypeLabel: 'label[for="applicantType"]',
  applicantTypeSelectedOption: '#applicantType option:selected',
  continueButton: '#continue',
  cancelLink: '#cancelCaseType a',
  errorSummary: '.govuk-error-summary',
  errorSummaryLinks: '.govuk-error-summary a',
  caseTypeError: '#caseType-error-message',
  applicantTypeError: '#applicantType-error-message',
  caseDetails: {
    backLink: '.govuk-back-link',
    caption: '.govuk-caption-l',
    heading: 'h1',
    caseTypeRow: '#caseDetailsCaseType',
    caseTypeValue: '#caseDetailsCaseTypeValue',
    applicantTypeRow: '#caseDetailsApplicantType',
    applicantTypeValue: '#caseDetailsApplicantTypeValue',
    taskNames: '.govuk-task-list__name-and-hint',
    partyDetails: '#partyDetails',
    order: '#order',
    additionalInformation: '#additionalInformation',
    respondentItem: '#respondentItem',
    respondentLink: '#respondentItem a',
    respondentStatus: '#respondentStatus',
    applicantItem: '#applicantItem',
    applicantLink: '#applicantItem a',
    applicantStatus: '#applicantStatus',
    centralAuthorityItem: '#centralAuthorityItem',
    centralAuthorityLink: '#centralAuthorityItem a',
    centralAuthorityStatus: '#centralAuthorityStatus',
    orderDetailsItem: '#orderDetailsItem',
    orderDetailsLink: '#orderDetailsItem a',
    orderDetailsStatus: '#orderDetailsStatus',
    orderTermsItem: '#orderTermsItem',
    orderTermsLink: '#orderTermsItem a',
    orderTermsStatus: '#orderTermsStatus',
    interestAndIndexationItem: '#interestAndIndexationItem',
    interestAndIndexationLink: '#interestAndIndexationItem a',
    interestAndIndexationStatus: '#interestAndIndexationStatus',
    managingPaymentsItem: '#managingPaymentsItem',
    managingPaymentsLink: '#managingPaymentsItem a',
    managingPaymentsStatus: '#managingPaymentsStatus',
    commentsAndNotesItem: '#commentsAndNotesItem',
    commentsAndNotesLink: '#commentsAndNotesItem a',
    commentsAndNotesStatus: '#commentsAndNotesStatus',
    blockingGuidance: '#checkCaseBlockingGuidance',
    checkCaseButton: '#checkCaseButton',
    cancelLink: '#cancelCaseCreation',
  },
  respondentDetails: {
    heading: 'h1',
    sectionHeadings: 'h2',
    title: '#respondent_title',
    firstNames: '#respondent_first_names',
    lastName: '#respondent_last_name',
    addAliases: '#respondent_add_aliases',
    aliasesConditional: '#respondentAliasesConditional-conditional',
    aliasFirstNames: 'input[id^="respondent_alias_first_names_"]',
    aliasLastNames: 'input[id^="respondent_alias_last_name_"]',
    aliasFirstName: (index: number) => `#respondent_alias_first_names_${index}`,
    aliasLastName: (index: number) => `#respondent_alias_last_name_${index}`,
    addAliasButton: '#addRespondentAlias',
    removeAliasLink: '#respondentAliasesConditional-conditional a.govuk-link',
    dateOfBirth: '#respondent_date_of_birth',
    nationalInsuranceNumber: '#respondent_national_insurance_number',
    otherPersonalInformation: '#respondent_other_personal_information',
    mainEmailAddress: '#respondent_main_email_address',
    otherEmailAddress: '#respondent_other_email_address',
    mainTelephoneNumber: '#respondent_main_telephone_number',
    otherTelephoneNumber: '#respondent_other_telephone_number',
    addressLine1: '#respondent_address_line_1',
    addressLine2: '#respondent_address_line_2',
    addressLine3: '#respondent_address_line_3',
    addressLine4: '#respondent_address_line_4',
    addressLine5: '#respondent_address_line_5',
    postalOrZipCode: '#respondent_postal_or_zip_code',
    countryId: '#respondent_country_id',
    countryAutocomplete: '#respondent_country_id-autocomplete',
    countryOptions: '#respondent_country_id-autocomplete__listbox [role="option"]',
    sendCorrespondenceToThirdParty: '#respondent_send_correspondence_to_third_party',
    thirdPartyConditional: '#respondentThirdPartyConditional-conditional',
    thirdPartyNameOrOrganisation: '#respondent_third_party_name_or_organisation',
    thirdPartyRelationship: '#respondent_third_party_relationship',
    thirdPartyReference: '#respondent_third_party_reference',
    thirdPartyAddressLine1: '#respondent_third_party_address_line_1',
    thirdPartyAddressLine2: '#respondent_third_party_address_line_2',
    thirdPartyAddressLine3: '#respondent_third_party_address_line_3',
    thirdPartyAddressLine4: '#respondent_third_party_address_line_4',
    thirdPartyAddressLine5: '#respondent_third_party_address_line_5',
    thirdPartyPostalOrZipCode: '#respondent_third_party_postal_or_zip_code',
    thirdPartyCountry: '#respondent_third_party_country_id',
    addEmployerDetails: '#respondent_add_employer_details',
    employerConditional: '#respondentEmployerConditional-conditional',
    employerName: '#respondent_employer_name',
    employeeReference: '#respondent_employee_reference',
    employerEmailAddress: '#respondent_employer_email_address',
    employerTelephoneNumber: '#respondent_employer_telephone_number',
    employerAddressLine1: '#respondent_employer_address_line_1',
    employerAddressLine2: '#respondent_employer_address_line_2',
    employerAddressLine3: '#respondent_employer_address_line_3',
    employerAddressLine4: '#respondent_employer_address_line_4',
    employerAddressLine5: '#respondent_employer_address_line_5',
    employerPostalOrZipCode: '#respondent_employer_postal_or_zip_code',
    employerCountryId: '#respondent_employer_country_id',
    employerCountryAutocomplete: '#respondent_employer_country_id-autocomplete',
    employerCountryOptions: '#respondent_employer_country_id-autocomplete__listbox [role="option"]',
    restrictedInformation: '#respondent_restricted_information',
    restrictedInformationConditional: '#respondentRestrictedInformationConditional-conditional',
    restrictedInformationReason: '#respondent_restricted_information_reason',
    returnToCaseDetails: '#returnToCaseDetails',
    cancelLink: '#cancelRespondentDetails a',
    errorSummary: '.govuk-error-summary',
    errorSummaryLinks: '.govuk-error-summary a',
    firstNamesError: '#respondent_first_names-error-message',
    lastNameError: '#respondent_last_name-error-message',
    aliasFirstNameError: (index: number) => `#respondent_alias_first_names_${index}-error-message`,
    aliasLastNameError: (index: number) => `#respondent_alias_last_name_${index}-error-message`,
    addressLine1Error: '#respondent_address_line_1-error-message',
    countryError: '#respondent_country_id-autocomplete-error-message',
    thirdPartyNameOrOrganisationError: '#respondent_third_party_name_or_organisation-error-message',
    thirdPartyRelationshipError: '#respondent_third_party_relationship-error-message',
    thirdPartyAddressLine1Error: '#respondent_third_party_address_line_1-error-message',
    thirdPartyCountryError: '#respondent_third_party_country_id-error-message',
    employerNameError: '#respondent_employer_name-error-message',
    employerAddressLine1Error: '#respondent_employer_address_line_1-error-message',
    employerCountryError: '#respondent_employer_country_id-autocomplete-error-message',
    restrictedInformationReasonError: '#respondent_restricted_information_reason-error-message',
  },
  applicantIndividual: {
    heading: 'h1',
    sectionHeadings: 'h2',
    title: '#applicant_title',
    firstNames: '#applicant_first_names',
    lastName: '#applicant_last_name',
    addAliases: '#applicant_add_aliases',
    aliasesConditional: '#applicantAliasesConditional-conditional',
    aliasFirstNames: 'input[id^="applicant_alias_first_names_"]',
    aliasLastNames: 'input[id^="applicant_alias_last_name_"]',
    aliasFirstName: (index: number) => `#applicant_alias_first_names_${index}`,
    aliasLastName: (index: number) => `#applicant_alias_last_name_${index}`,
    addAliasButton: '#addApplicantAlias',
    removeAliasLink: '#applicantAliasesConditional-conditional a.govuk-link',
    dateOfBirth: '#applicant_date_of_birth',
    dateOfBirthCalendarButton: '#applicant_date_of_birth + .moj-js-datepicker-toggle',
    mainEmailAddress: '#applicant_main_email_address',
    otherEmailAddress: '#applicant_other_email_address',
    mainTelephoneNumber: '#applicant_main_telephone_number',
    otherTelephoneNumber: '#applicant_other_telephone_number',
    addressLine1: '#applicant_address_line_1',
    addressLine2: '#applicant_address_line_2',
    addressLine3: '#applicant_address_line_3',
    addressLine4: '#applicant_address_line_4',
    addressLine5: '#applicant_address_line_5',
    postalOrZipCode: '#applicant_postal_or_zip_code',
    countryId: '#applicant_country_id',
    countryAutocomplete: '#applicant_country_id-autocomplete',
    countryOptions: '#applicant_country_id-autocomplete__listbox [role="option"]',
    sendCorrespondenceToThirdParty: '#applicant_send_correspondence_to_third_party',
    thirdPartyConditional: '#applicantThirdPartyConditional-conditional',
    thirdPartyNameOrOrganisation: '#applicant_third_party_name_or_organisation',
    thirdPartyRelationship: '#applicant_third_party_relationship',
    thirdPartyReference: '#applicant_third_party_reference',
    thirdPartyAddressLine1: '#applicant_third_party_address_line_1',
    thirdPartyAddressLine2: '#applicant_third_party_address_line_2',
    thirdPartyAddressLine3: '#applicant_third_party_address_line_3',
    thirdPartyAddressLine4: '#applicant_third_party_address_line_4',
    thirdPartyAddressLine5: '#applicant_third_party_address_line_5',
    thirdPartyPostalOrZipCode: '#applicant_third_party_postal_or_zip_code',
    thirdPartyCountry: '#applicant_third_party_country_id',
    bankTypeGroup: '#applicant_bank_type',
    bankTypeRadios: 'input[name="applicant_bank_type"]',
    bankTypeRadio: (value: string) => `#applicant_bank_type-${value}`,
    ukBankConditional: '#applicantUkBankConditional',
    ukBankNameOnAccount: '#applicant_uk_bank_name_on_account',
    ukBankSortCode: '#applicant_uk_bank_sort_code',
    ukBankAccountNumber: '#applicant_uk_bank_account_number',
    ukBankPaymentReference: '#applicant_uk_bank_payment_reference',
    nonUkBankConditional: '#applicantNonUkBankConditional',
    nonUkBankNameOnAccount: '#applicant_non_uk_bank_name_on_account',
    nonUkBankAccountNumber: '#applicant_non_uk_bank_account_number',
    nonUkBankPaymentReference: '#applicant_non_uk_bank_payment_reference',
    nonUkBankBicSwiftCode: '#applicant_non_uk_bank_bic_swift_code',
    nonUkBankIban: '#applicant_non_uk_bank_iban',
    nonUkBankName: '#applicant_non_uk_bank_name',
    nonUkBankBranchSortCode: '#applicant_non_uk_bank_branch_sort_code',
    restrictedInformation: '#applicant_restricted_information',
    restrictedInformationConditional: '#applicantRestrictedInformationConditional-conditional',
    restrictedInformationReason: '#applicant_restricted_information_reason',
    returnToCaseDetails: '#returnToCaseDetails',
    cancelLink: '#cancelApplicantDetails a',
    errorSummary: '.govuk-error-summary',
    errorSummaryLinks: '.govuk-error-summary a',
    titleError: '#applicant_title-error-message',
    firstNamesError: '#applicant_first_names-error-message',
    lastNameError: '#applicant_last_name-error-message',
    aliasFirstNameError: (index: number) => `#applicant_alias_first_names_${index}-error-message`,
    aliasLastNameError: (index: number) => `#applicant_alias_last_name_${index}-error-message`,
    dateOfBirthError: '#applicant_date_of_birth-error-message',
    mainEmailAddressError: '#applicant_main_email_address-error-message',
    otherEmailAddressError: '#applicant_other_email_address-error-message',
    mainTelephoneNumberError: '#applicant_main_telephone_number-error-message',
    otherTelephoneNumberError: '#applicant_other_telephone_number-error-message',
    addressLine1Error: '#applicant_address_line_1-error-message',
    addressLine2Error: '#applicant_address_line_2-error-message',
    addressLine3Error: '#applicant_address_line_3-error-message',
    addressLine4Error: '#applicant_address_line_4-error-message',
    addressLine5Error: '#applicant_address_line_5-error-message',
    postalOrZipCodeError: '#applicant_postal_or_zip_code-error-message',
    countryError: '#applicant_country_id-autocomplete-error-message',
    thirdPartyNameOrOrganisationError: '#applicant_third_party_name_or_organisation-error-message',
    thirdPartyRelationshipError: '#applicant_third_party_relationship-error-message',
    thirdPartyReferenceError: '#applicant_third_party_reference-error-message',
    thirdPartyAddressLine1Error: '#applicant_third_party_address_line_1-error-message',
    thirdPartyAddressLine2Error: '#applicant_third_party_address_line_2-error-message',
    thirdPartyAddressLine3Error: '#applicant_third_party_address_line_3-error-message',
    thirdPartyAddressLine4Error: '#applicant_third_party_address_line_4-error-message',
    thirdPartyAddressLine5Error: '#applicant_third_party_address_line_5-error-message',
    thirdPartyPostalOrZipCodeError: '#applicant_third_party_postal_or_zip_code-error-message',
    thirdPartyCountryError: '#applicant_third_party_country_id-error-message',
    bankTypeError: '#applicant_bank_type-error-message',
    ukBankNameOnAccountError: '#applicant_uk_bank_name_on_account-error-message',
    ukBankSortCodeError: '#applicant_uk_bank_sort_code-error-message',
    ukBankAccountNumberError: '#applicant_uk_bank_account_number-error-message',
    ukBankPaymentReferenceError: '#applicant_uk_bank_payment_reference-error-message',
    nonUkBankNameOnAccountError: '#applicant_non_uk_bank_name_on_account-error-message',
    nonUkBankAccountNumberError: '#applicant_non_uk_bank_account_number-error-message',
    nonUkBankBicSwiftCodeError: '#applicant_non_uk_bank_bic_swift_code-error-message',
    nonUkBankIbanError: '#applicant_non_uk_bank_iban-error-message',
    nonUkBankBranchSortCodeError: '#applicant_non_uk_bank_branch_sort_code-error-message',
    restrictedInformationReasonError: '#applicant_restricted_information_reason-error-message',
  },
} as const;
