export const ORDER_TERMS_INPUT_COPY = {
  amountRequired: 'Enter an amount',
  numeric: 'Enter numbers only',
  expiryInvalid: 'Enter a valid expiry date',
  birthPast: 'Child’s date of birth must be in the past',
  expiryRequired: 'Enter an expiry date',
  birthRequired: 'Enter child’s date of birth',
  childRequired: 'Enter child’s name',
  childTooLong: 'Child’s name must be 60 characters or fewer',
  birthInvalid: 'Enter a valid child’s date of birth',
  precision: 'Enter an amount with no more than 2 decimal places',
  amountMin: 'Amount must be 0 or more',
  amountMax: 'Amount must be 9999999999.99 or less',
  arrearsMin: 'Arrears must be 0 or more',
  arrearsMax: 'Arrears must be 9999999999.99 or less',
  expiryMin: 'Expiry date must be on or after 1900-01-01',
  expiryMax: 'Expiry date must be on or before 2100-12-31',
  birthMin: 'Child’s date of birth must be on or after 1900-01-01',
  shortTextMin: 'Short text must be 2 characters or more',
  shortTextMax: 'Short text must be 5 characters or fewer',
  longTextMax: 'Long text must be 100 characters or fewer',
  integerInvalid: 'Enter a whole number within the supported range',
  integerMin: 'Count must be 1 or more',
  integerMax: 'Count must be 5 or less',
};
