import type {
  IAbstractFormBaseFieldError,
  IAbstractFormBaseFieldErrors,
} from '@hmcts/opal-frontend-common/components/abstract/abstract-form-base/interfaces';

export interface ICasesCreateCasefileApplicantOrganisationFieldErrors extends IAbstractFormBaseFieldErrors {
  create_casefile_applicant_organisation_name: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_foreign_authority_reference: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_main_email_address: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_other_email_address: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_main_telephone_number: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_other_telephone_number: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_address_line_1: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_address_line_2: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_address_line_3: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_address_line_4: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_address_line_5: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_postal_or_zip_code: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_country_id: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_bank_type: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_uk_bank_name_on_account: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_uk_bank_sort_code: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_uk_bank_account_number: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_uk_bank_payment_reference: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_non_uk_bank_name_on_account: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_non_uk_bank_bic_swift_code: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_non_uk_bank_iban: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_non_uk_bank_payment_reference: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_non_uk_bank_name: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_non_uk_bank_branch_sort_code: IAbstractFormBaseFieldError;
  create_casefile_applicant_organisation_non_uk_bank_account_number: IAbstractFormBaseFieldError;
}
