import type { ICasesCreateCasefilePartyAlias } from '../../interfaces/cases-create-casefile-party-alias.interface';
import type { CasesCreateCasefileApplicantBankType } from '../../types/cases-create-casefile-applicant-bank-type.type';

export interface ICasesCreateCasefileApplicantIndividualFormData {
  create_casefile_applicant_individual_title: string | null;
  create_casefile_applicant_individual_first_names: string | null;
  create_casefile_applicant_individual_last_name: string | null;
  create_casefile_applicant_individual_add_aliases: boolean;
  create_casefile_applicant_individual_aliases: ICasesCreateCasefilePartyAlias[];
  create_casefile_applicant_individual_date_of_birth: string | null;
  create_casefile_applicant_individual_main_email_address: string | null;
  create_casefile_applicant_individual_other_email_address: string | null;
  create_casefile_applicant_individual_main_telephone_number: string | null;
  create_casefile_applicant_individual_other_telephone_number: string | null;
  create_casefile_applicant_individual_address_line_1: string | null;
  create_casefile_applicant_individual_address_line_2: string | null;
  create_casefile_applicant_individual_address_line_3: string | null;
  create_casefile_applicant_individual_address_line_4: string | null;
  create_casefile_applicant_individual_address_line_5: string | null;
  create_casefile_applicant_individual_postal_or_zip_code: string | null;
  create_casefile_applicant_individual_country_id: number | null;
  create_casefile_applicant_individual_send_correspondence_to_third_party: boolean;
  create_casefile_applicant_individual_third_party_name_or_organisation: string | null;
  create_casefile_applicant_individual_third_party_relationship: string | null;
  create_casefile_applicant_individual_third_party_reference: string | null;
  create_casefile_applicant_individual_third_party_address_line_1: string | null;
  create_casefile_applicant_individual_third_party_address_line_2: string | null;
  create_casefile_applicant_individual_third_party_address_line_3: string | null;
  create_casefile_applicant_individual_third_party_address_line_4: string | null;
  create_casefile_applicant_individual_third_party_address_line_5: string | null;
  create_casefile_applicant_individual_third_party_postal_or_zip_code: string | null;
  create_casefile_applicant_individual_third_party_country_id: number | null;
  create_casefile_applicant_individual_bank_type: CasesCreateCasefileApplicantBankType | null;
  create_casefile_applicant_individual_uk_bank_name_on_account: string | null;
  create_casefile_applicant_individual_uk_bank_sort_code: string | null;
  create_casefile_applicant_individual_uk_bank_account_number: string | null;
  create_casefile_applicant_individual_uk_bank_payment_reference: string | null;
  create_casefile_applicant_individual_non_uk_bank_name_on_account: string | null;
  create_casefile_applicant_individual_non_uk_bank_account_number: string | null;
  create_casefile_applicant_individual_non_uk_bank_payment_reference: string | null;
  create_casefile_applicant_individual_non_uk_bank_bic_swift_code: string | null;
  create_casefile_applicant_individual_non_uk_bank_iban: string | null;
  create_casefile_applicant_individual_non_uk_bank_name: string | null;
  create_casefile_applicant_individual_non_uk_bank_branch_sort_code: string | null;
  create_casefile_applicant_individual_restricted_information: boolean;
  create_casefile_applicant_individual_restricted_information_reason: string | null;
}
