import type { ICasesCreateCasefileApplicantAlias } from '../../interfaces/cases-create-casefile-applicant-alias.interface';
import type { CasesCreateCasefileApplicantBankType } from '../../types/cases-create-casefile-applicant-bank-type.type';

export interface ICasesCreateCasefileApplicantIndividualFormData {
  applicant_title: string | null;
  applicant_first_names: string | null;
  applicant_last_name: string | null;
  applicant_add_aliases: boolean;
  applicant_aliases: ICasesCreateCasefileApplicantAlias[];
  applicant_date_of_birth: string | null;
  applicant_main_email_address: string | null;
  applicant_other_email_address: string | null;
  applicant_main_telephone_number: string | null;
  applicant_other_telephone_number: string | null;
  applicant_address_line_1: string | null;
  applicant_address_line_2: string | null;
  applicant_address_line_3: string | null;
  applicant_address_line_4: string | null;
  applicant_address_line_5: string | null;
  applicant_postal_or_zip_code: string | null;
  applicant_country_id: number | null;
  applicant_send_correspondence_to_third_party: boolean;
  applicant_third_party_name_or_organisation: string | null;
  applicant_third_party_relationship: string | null;
  applicant_third_party_reference: string | null;
  applicant_third_party_address_line_1: string | null;
  applicant_third_party_address_line_2: string | null;
  applicant_third_party_address_line_3: string | null;
  applicant_third_party_address_line_4: string | null;
  applicant_third_party_address_line_5: string | null;
  applicant_third_party_postal_or_zip_code: string | null;
  applicant_third_party_country_id: number | null;
  applicant_bank_type: CasesCreateCasefileApplicantBankType | null;
  applicant_uk_bank_name_on_account: string | null;
  applicant_uk_bank_sort_code: string | null;
  applicant_uk_bank_account_number: string | null;
  applicant_uk_bank_payment_reference: string | null;
  applicant_non_uk_bank_name_on_account: string | null;
  applicant_non_uk_bank_account_number: string | null;
  applicant_non_uk_bank_payment_reference: string | null;
  applicant_non_uk_bank_bic_swift_code: string | null;
  applicant_non_uk_bank_iban: string | null;
  applicant_non_uk_bank_name: string | null;
  applicant_non_uk_bank_branch_sort_code: string | null;
  applicant_restricted_information: boolean;
  applicant_restricted_information_reason: string | null;
}
