import type {
  IAbstractFormBaseFieldError,
  IAbstractFormBaseFieldErrors,
} from '@hmcts/opal-frontend-common/components/abstract/abstract-form-base/interfaces';

export interface ICasesCreateCasefileApplicantIndividualFieldErrors extends IAbstractFormBaseFieldErrors {
  create_casefile_applicant_individual_title: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_first_names: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_last_name: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_alias_first_names_0: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_alias_last_name_0: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_alias_first_names_1: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_alias_last_name_1: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_alias_first_names_2: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_alias_last_name_2: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_alias_first_names_3: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_alias_last_name_3: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_alias_first_names_4: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_alias_last_name_4: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_date_of_birth: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_main_email_address: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_other_email_address: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_main_telephone_number: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_other_telephone_number: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_address_line_1: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_address_line_2: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_address_line_3: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_address_line_4: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_address_line_5: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_postal_or_zip_code: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_country_id: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_third_party_name_or_organisation: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_third_party_relationship: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_third_party_reference: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_third_party_address_line_1: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_third_party_address_line_2: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_third_party_address_line_3: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_third_party_address_line_4: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_third_party_address_line_5: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_third_party_postal_or_zip_code: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_third_party_country_id: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_bank_type: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_uk_bank_name_on_account: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_uk_bank_sort_code: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_uk_bank_account_number: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_uk_bank_payment_reference: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_non_uk_bank_name_on_account: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_non_uk_bank_account_number: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_non_uk_bank_bic_swift_code: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_non_uk_bank_iban: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_non_uk_bank_branch_sort_code: IAbstractFormBaseFieldError;
  create_casefile_applicant_individual_restricted_information_reason: IAbstractFormBaseFieldError;
}
